-- Exported values from CurseForge

FishingTranslations["koKR"] = {
	ABOUT_TAB = "정보", -- Needs review
	ADD = "추가",
	ADDFISHIEMSG = "%s를 %s에 추가합니다.", -- Needs review
	ADDSCHOOLMSG = "'%s'를 %s에 추가합니다.", -- Needs review
	ALLZOMGPETS = "모든 애완동물 포함", -- Needs review
	BINDING_NAME_FISHINGBUDDY_GOFISHING = "장비 착용 및 낚시 시작", -- Needs review
	BINDING_NAME_FISHINGBUDDY_SWITCH = "낚시 장비로 교체", -- Needs review
	BINDING_NAME_FISHINGBUDDY_TOGGLE = "#NAME# 창 토글",
	BINDING_NAME_TOGGLEFISHINGBUDDY_LOC = "#NAME# 위치 창 토글",
	BINDING_NAME_TOGGLEFISHINGBUDDY_OPT = "#NAME# 옵션 창 토글", -- Needs review
	BOBBER_NAME = "낚시찌",
	CAST = " 캐스트",
	CAUGHTTHISMANY = "획득량:",
	CAUGHTTHISTOTAL = "총획득량:",
	CAUGHT_IN_ZONES = "획득 장소: %s", -- Needs review
	CHECK = "체크",
	CLEANUP = "삭제",
	CLEANUP_DONEMSG = "기존 |c#RED#%s|r: %s 설정이 삭제 되었습니다.", -- Needs review
	CLEANUP_NONEMSG = "기존 설정이 없습니다.",
	CLEANUP_NOOLDMSG = "|c#GREEN#%s|r 사용자에 대한 기존 설정은 없습니다 .", -- Needs review
	CLEANUP_WILLMSG = "|c#RED#%s|r: %s 기존 설정을 계속 사용합니다.", -- Needs review
	CLICKTOSWITCH_INFO = "선택하면, 좌클릭으로 장비 교체, 비선택 시에는 낚시 도우미 창을 엽니다.", -- Needs review
	CLICKTOSWITCH_ONOFF = "클릭 시 교체", -- Needs review
	COMPATIBLE_SWITCHER = "정확한 복장을 찾을 수 없습니다.",
	CONFIG_ALWAYSLURE_INFO = "선택하면, 낚시대에 미끼가 없으면 항상 미끼를 답니다.", -- Needs review
	CONFIG_ALWAYSLURE_ONOFF = "항상 미끼 사용",
	CONFIG_AUTOLOOT_INFO = "선택하면, 잡은 물고기를 자동으로 루팅합니다.",
	CONFIG_AUTOLOOT_ONOFF = "자동 루팅",
	CONFIG_AUTOOPEN_INFO = "선택하면, 더블 클릭을 낚시 퀘스트 아이템을 여는 것으로 사용", -- Needs review
	CONFIG_AUTOOPEN_ONOFF = "퀘스트 아이템 열기", -- Needs review
	CONFIG_BGSOUNDS_INFO = "선택하면, 게임 창이 백그라운드에 있을 때 소리가 납니다.", -- Needs review
	CONFIG_BGSOUNDS_ONOFF = "배경음",
	CONFIG_CONTESTS_INFO = "낚시왕 선발대회에 대한 타이머 표시", -- Needs review
	CONFIG_CONTESTS_ONOFF = "낚시왕 선발대회 지원", -- Needs review
	CONFIG_EASYCAST_INFO = "더블 우-클릭 낚시 사용",
	CONFIG_EASYCAST_ONOFF = "쉬운 낚시",
	CONFIG_EASYLURES_INFO = "낚시를 시작하기 전 항상 낚시대에 미끼를 답니다",
	CONFIG_EASYLURES_ONOFF = "쉬운 미끼 달기",
	CONFIG_ENHANCESOUNDS_INFO = "낚시 중 낚시 효과음을 최대로, 배경음은 최소로 음량을 조절합니다",
	CONFIG_ENHANCESOUNDS_ONOFF = "낚시음 확대",
	CONFIG_FINDFISH_INFO = "물고기때 켜고 찾기",
	CONFIG_FINDFISH_ONOFF = "물고기 찾기",
	CONFIG_FISHINGBUDDY_ONOFF = "낚시 도우미", -- Needs review
	CONFIG_FISHWATCHONLY_INFO = "획득량 표시를 낚시중일 때만 표시합니다",
	CONFIG_FISHWATCHONLY_ONOFF = "낚시 중일 때만 표시",
	CONFIG_FISHWATCHPERCENT_INFO = "획득량 표시에 각각의 어류의 획득 백분률을 표시합니다.",
	CONFIG_FISHWATCHPERCENT_ONOFF = "획득 백분률 표시",
	CONFIG_FISHWATCHSKILL_INFO = "현재 낚시 기술의 숙련도와 현재 지역에서 낚시를 하는데 요구되는 숙련도를 표시합니다",
	CONFIG_FISHWATCHSKILL_ONOFF = "현재 숙련도 표시",
	CONFIG_FISHWATCHTIME_INFO = "낚시대를 착용하고 있던 총 시간을 표시합니다",
	CONFIG_FISHWATCHTIME_ONOFF = "총 낚시 시간 표시",
	CONFIG_FISHWATCHZONE_INFO = "물고기를 낚고 있는 현재 지역을 표시합니다.",
	CONFIG_FISHWATCHZONE_ONOFF = "현재 지역",
	CONFIG_FISHWATCH_INFO = "현재 지역에서 획득한 어류의 획득량을 표시합니다.",
	CONFIG_FISHWATCH_ONOFF = "획득량",
	CONFIG_MINIMAPBUTTON_INFO = "미니맵에 #NAME# 아이콘을 표시합니다",
	CONFIG_MINIMAPBUTTON_ONOFF = "미니맵 버튼 보기",
	CONFIG_ONLYMINE_INFO = "선택하면, 쉬운 낚시 기능은 낚시용 복장에 설정된 낚싯대를 장비 하고 있을 때만 사용합니다.",
	CONFIG_ONLYMINE_ONOFF = "낚싯대만 장비", -- Needs review
	CONFIG_OUTFITTER_TEXT = "낚시 숙련 보너스: %s#BR#Draznar's의 복장 점수: %d ",
	CONFIG_SHOWLOCATIONZONES_INFO = "대지역명과 소지역명을 모두 표시합니다.",
	CONFIG_SHOWLOCATIONZONES_ONOFF = "지역 보기",
	CONFIG_SHOWNEWFISHIES_INFO = "신규 어종을 획득하면 대화창에 메세지를 표시합니다.",
	CONFIG_SHOWNEWFISHIES_ONOFF = "신규 어종 표시",
	CONFIG_SHOWPOOLS_INFO = "선택하면, 미니맵에 알고 있는 물고기 때 위치를 표시", -- Needs review
	CONFIG_SHOWPOOLS_ONOFF = "물고기 때 보기", -- Needs review
	CONFIG_SORTBYPERCENT_INFO = "어류의 획득량을 이름 순이 아니라 획득량 순으로 정렬합니다.",
	CONFIG_SORTBYPERCENT_ONOFF = "획득량 정렬",
	CONFIG_SPARKLIES_INFO = "선택하면, 낚시하는 동안 물고기 떼의 번쩍거림을 더 돋보이게 함", -- Needs review
	CONFIG_SPARKLIES_ONOFF = "물고기 떼 번쩍거림 강화", -- Needs review
	CONFIG_STVPOOLSONLY_INFO = "사용할 경우 쉬운 낚시 기능은 물고기 떼에 마우스를 올려놔야만 작동합니다.",
	CONFIG_STVPOOLSONLY_ONOFF = "물고기 떼에만 낚시", -- Needs review
	CONFIG_STVTIMER_INFO = "선택하면, 낚시왕 선발대회가 시작하기 까지의 시간을 표시합니다.",
	CONFIG_STVTIMER_ONOFF = "낚시왕 선발대회 타이머",
	CONFIG_TOOLTIPS_INFO = "선택하면, 아이템 툴팁에 획득한 물고기에 대한 정보를 표시합니다.", -- Needs review
	CONFIG_TOOLTIPS_ONOFF = "툴팁에 낚시정보 표시",
	CONFIG_TURNOFFPVP_INFO = "낚시대를 장착 중일 때는 PVP 설정을 끕니다",
	CONFIG_TURNOFFPVP_ONOFF = "PVP 끔",
	CONFIG_USEACTION_INFO = "선택하면, #NAME# 는 낚시대 캐스팅 시 행동단축바의 버튼을 이용합니다.", -- Needs review
	CONFIG_USEACTION_ONOFF = "단축버튼 사용",
	COPPER_COIN = "동화",
	CURRENT = "현재",
	DESCRIPTION1 = "획득한 물고기에 대한 정보를 기록하고",
	DESCRIPTION2 = "낚시용 장비를 관리합니다.", -- Needs review
	ELAPSED = "경과",
	ELEM_WATER = "증기 양수기 표류물",
	FAILEDINIT = "정상적으로 설치되지 않았습니다.",
	FATLADYSINGS = "|c#RED#(%s) 낚시왕 선발대회 종료까지|r (%d:%02d 남음)", -- Needs review
	FISH = "물고기",
	FISHTYPES = "물고기 종류: %d", -- Needs review
	FLOATING_DEBRIS = "범선 잔해",
	FLOATING_WRECKAGE = "표류하는 잔해",
	FORCE = "강제",
	GOLD_COIN = "금화",
	HELP = "도움",
	HIDEINWATCHER = "해당 어종을 획득량 표시에 표시합니다.",
	HOURLY = "시간",
	KEYS_ALT_TEXT = "Alt",
	KEYS_CTRL_TEXT = "Control",
	KEYS_LABEL_TEXT = "적용키:",
	KEYS_NONE_TEXT = "없음",
	KEYS_SHIFT_TEXT = "Shift",
	LEFTCLICKTODRAG = "좌클릭으로 이동",
	LOCATIONS_INFO = "어디서 물고기를 낚았는 지 보여줍니다. (장소 별, 종류 별)", -- Needs review
	LOCATIONS_TAB = "위치",
	MINIMAPBUTTONPLACEMENT = "버튼 위치",
	MINIMAPBUTTONPLACEMENTTOOLTIP = "#NAME# 의 미니맵 버튼의 위치를 변경할 수 있습니다.",
	MINIMAPBUTTONRADIUS = "거리", -- Needs review
	MINIMAPBUTTONRADIUSTOOLTIP = "#NAME# 아이콘이 미니맵과의 얼마나 떨어져 있어야 하는는 지를 정합니다.", -- Needs review
	MINIMUMSKILL = "최소 숙련도: %d",
	NAME = "낚시 도우미",
	NODATAMSG = "사용 가능한 낚시 자료가 없습니다.",
	NONEAVAILABLE_MSG = "사용가능한 것이 없습니다.",
	NOREALM = "알 수 없는 서버", -- Needs review
	NOTLINKABLE = "<링크할 수 없는 아이템>",
	NOW = "지금",
	OFFSET_LABEL_TEXT = "Offset:",
	OIL_SPILL = "떠다니는 기름",
	OPTIONS_INFO = "#NAME# 옵션 설정", -- Needs review
	OPTIONS_TAB = "옵션",
	OUTFITS = "장비", -- Needs review
	POINT = "점",
	POINTS = "점",
	RANDOM = "임의", -- Needs review
	RAW = "생",
	REPLACE = "교체",
	RESET = "초기화",
	RIGGLE_BASSBAIT = "라글 바스베이트의 외침: 우승자가 결정되었습니다!  우승자는 (%a+) 입니다!", -- Needs review
	RIGHTCLICKFORMENU = "우클릭으로 메뉴 열기", -- Needs review
	ROLE_HELP_BUGS = "제작 도움 및 버그 수정", -- Needs review
	ROLE_HELP_SUGGESTIONS = "기능 제안", -- Needs review
	ROLE_TRANSLATE_DEDE = "독일어 번역", -- Needs review
	ROLE_TRANSLATE_ESES = "스페인어 번역", -- Needs review
	ROLE_TRANSLATE_FRFR = "프랑스어 번역", -- Needs review
	ROLE_TRANSLATE_KOKR = "한국어  번역", -- Needs review
	ROLE_TRANSLATE_RURU = "러시아어 번역", -- Needs review
	ROLE_TRANSLATE_ZHCN = "중국어(CN) 번역", -- Needs review
	ROLE_TRANSLATE_ZHTW = "중국어(TW) 번역", -- Needs review
	SCHOOL = "물고기 떼", -- Needs review
	SHOWFISHIES = "물고기 보기",
	SHOWFISHIES_INFO = "물고기 종류에 따라 낚시 기록을 봅니다",
	SHOWLOCATIONS = "위치",
	SHOWLOCATIONS_INFO = "장소에 따라 낚시 기록을 봅니다",
	SILVER_COIN = "은화",
	STVZONENAME = "가시덤불 골짜기", -- Needs review
	SWITCH = "교체",
	THANKS = "모두 감사합니다!", -- Needs review
	TIMELEFT = "%s는 %d:%02d 안에 끝남", -- Needs review
	TIMER = "타이머", -- Needs review
	TIMETOGO = "%s가 %d:%02d 안에 시작됨", -- Needs review
	TOOLTIP_HINT = "힌트:", -- Needs review
	TOOLTIP_HINTSWITCH = "장비 교체하려면 클릭", -- Needs review
	TOOLTIP_HINTTOGGLE = "#NAME# 창 열려면 클릭", -- Needs review
	TOOMANYFISHERMEN = "여러 개의 쉬운 낚시 기능을 가진 애드온이 설치되어 있습니다.",
	TOTAL = "합계",
	TOTALS = "합계",
	UPDATE = "업데이트",
	UPDATEDB = "자료 업데이트",
	UPDATEDB_MSG = "물고기 이름 %d 개를 업데이트 했습니다.", -- Needs review
	WATCHER = "획득량 표시",
	WATCHER_LOCK = "잠금",
	WATCHER_UNLOCK = "해제", -- Needs review
	WEEKLY = "주간",
}

