-- a grave 195.160
-- a circumflex	195.162
-- e circumflex 195.170
-- e grave 195.168
-- e acute 195.169

FishingTranslations["frFR"] = {
	ADD = "Ajout", -- Needs review
	ADDFISHIEMSG = "Ajout de %s au lieu %s.",
	ADDSCHOOLMSG = "Ajout de '%s' au lieu %s.",
	BINDING_NAME_FISHINGBUDDY_GOFISHING = "S'habiller et aller p\195\170cher", -- Needs review
	BINDING_NAME_FISHINGBUDDY_SWITCH = "Porter l'\195\169quipement de p\195\170che",
	BINDING_NAME_FISHINGBUDDY_TOGGLE = "Activer la fen\195\170tre #NAME#",
	BINDING_NAME_TOGGLEFISHINGBUDDY_LOC = "Activer le panneau de r\195\169gion #NAME#",
	BINDING_NAME_TOGGLEFISHINGBUDDY_OPT = "Activer le panneau d'options #NAME#",
	BOBBER_NAME = "Bouchon",
	CAST = "Lancer le bouchon",
	CAUGHTTHISMANY = "Pris :",
	CAUGHTTHISTOTAL = "Total :",
	CAUGHT_IN_ZONES = "Pris \195\160 :", -- Needs review
	CHECK = "V\195\169rifier", -- Needs review
	CLEANUP = "Nettoyer",
	CLEANUP_DONEMSG = "Anciens param\195\168tres supprim\195\169s pour |c#RED#%s|r: %s.", -- Needs review
	CLEANUP_NONEMSG = "Il ne reste plus d'anciens r\195\169glages.", -- Needs review
	CLEANUP_NOOLDMSG = "Il n'y a pas d'ancien r\195\169glages pour le joueur |c#GREEN#%s|r.", -- Needs review
	CLEANUP_WILLMSG = "Ancien r\195\169glages supprim\195\169s pour |c#RED#%s|r: %s.", -- Needs review
	CLICKTOSWITCH_INFO = "Si actif, un clic gauche change l'\195\169quipement, sinon, il affiche la fen\195\170tre Fishing Buddy.",
	CLICKTOSWITCH_ONOFF = "Cliquer pour changer",
	COMPATIBLE_SWITCHER = "Pas de gestionnaire d'\195\169quipement compatible trouv\195\169.", -- Needs review
	CONFIG_ALWAYSLURE_INFO = "Si actif, appliquer un app\195\162t chaque fois qu'aucun n'est pr\195\169sent.", -- Needs review
	CONFIG_EASYCAST_INFO = "Active le lancer de bouchon par double-clic-droit.",
	CONFIG_EASYCAST_ONOFF = "Lancer le bouchon facilement",
	CONFIG_EASYLURES_ONOFF = "App\195\162ts faciles", -- Needs review
	CONFIG_ENHANCESOUNDS_INFO = "Si actif, augmente le volume des sons et baisse les volumes de l'ambiance afin de mieux entendre le bouchon.",
	CONFIG_ENHANCESOUNDS_ONOFF = "Augmente les bruits de p\195\170che",
	CONFIG_FINDFISH_INFO = "Activer la fonction \"Trouver des poissons\" lorsque l'on est \195\169quip\195\169 pour la p\195\170che", -- Needs review
	CONFIG_FINDFISH_ONOFF = "Trouver des poissons",
	CONFIG_FISHWATCHONLY_INFO = "Montrer seulement les poissons lorsque vous \195\170tes en train de p\195\169cher.",
	CONFIG_FISHWATCHONLY_ONOFF = "Seulement en p\195\169chant",
	CONFIG_FISHWATCHPERCENT_INFO = "Affiche les pourcentages pour chaque type de poisson dans la zone de texte.",
	CONFIG_FISHWATCHPERCENT_ONOFF = "Montre les pourcentages",
	CONFIG_FISHWATCHSKILL_INFO = "Affiche votre niveau de p\195\170che actuel ainsi que les am\195\169liorations dans la zone de texte.",
	CONFIG_FISHWATCHSKILL_ONOFF = "Niveau actuel",
	CONFIG_FISHWATCHTIME_INFO = "Afficher le temps \195\169coul\195\169 depuis la derni\195\168re fois qu'une canne \195\160 p\195\168che a \195\169t\195\169 \195\169quip\195\169e", -- Needs review
	CONFIG_FISHWATCHTIME_ONOFF = "Afficher le temps \195\169coul\195\169", -- Needs review
	CONFIG_FISHWATCHZONE_INFO = "Affiche la zone courante dans la zone de texte.",
	CONFIG_FISHWATCHZONE_ONOFF = "Zone courante",
	CONFIG_FISHWATCH_INFO = "Affiche une zone de texte avec les poissons d\195\169j\195\160 p\195\169ch\195\169s dans la zone courante.",
	CONFIG_FISHWATCH_ONOFF = "Archive des poissons",
	CONFIG_MINIMAPBUTTON_INFO = "Affiche le bouton de #NAME# autour de la minimap.",
	CONFIG_MINIMAPBUTTON_ONOFF = "Affiche le bouton de la minimap.",
	CONFIG_SHOWNEWFISHIES_INFO = "Affiche un message dans la zone de texte quand un nouveau poisson est p\195\169ch\195\169.",
	CONFIG_SHOWNEWFISHIES_ONOFF = "Montrer les nouveaux poissons",
	CONFIG_SORTBYPERCENT_INFO = "Trie l'affichage par quantit\195\169 de poissons p\195\169ch\195\169s au lieu du nom.", -- Needs review
	CONFIG_SORTBYPERCENT_ONOFF = "Trie par quantit\195\169 de poissons",
	CONFIG_STVTIMER_INFO = "Si actif, un compteur sera affich\195\169 indiquant le temps restant avant le debut et avant la fin du concours.",
	CONFIG_STVTIMER_ONOFF = "Timer du concours de p\195\170che",
	COPPER_COIN = "Pi\195\169ce de cuivre",
	CURRENT_HELP = "|c#GREEN#/fb #CURRENT# #RESET#|r#BRSPCS#Remet a z\195\169ro les poissons pris au cours de cette session.",
	DESCRIPTION1 = "Se souvient des poissons pris et",
	DESCRIPTION2 = "organise votre \195\169quipement.",
	EXTRAVAGANZA = "Le concours de p\195\170che",
	GOLD_COIN = "Pi\195\169ce d'or",
	HELP = "Aide",
	HOURLY = "\190\160 l'heure", -- Needs review
	KEYS_CTRL_TEXT = "CTRL",
	KEYS_LABEL_TEXT = "Touches :",
	KEYS_NONE_TEXT = "Aucune",
	LAGER = "Brune du capitaine Rumsey",
	LEFTCLICKTODRAG = "Clique gauche pour d\195\169placer",
	LOCATIONS_INFO = "Affiche les informations de p\195\170che locales", -- Needs review
	LOCATIONS_TAB = "Lieux",
	MINIMAPBUTTONPLACEMENT = "Position du bouton",
	MINIMAPBUTTONPLACEMENTTOOLTIP = "Permet de d\195\169placer le bouton de #NAME# autour de la minimap",
	OPTIONS_INFO = "R\195\168gle les options",
	POST_HELP = "Vous pouvez assigner une touche pour afficher/cacher la fen\195\170tre et/ou#BR#changer d'\195\169quipement dans la fen\195\170tre \"Raccourcis\".",
	PRE_HELP = "Vous pouvez utiliser |c#GREEN#/fishingbuddy|r ou |c#GREEN#/fb|r pour toutes les commandes#BR#|c#GREEN#/fb|r: seul, affiche/cache la fen\195\170tre de FishingBuddy#BR#|c#GREEN#/fb #HELP#|r: affiche ce message",
	SHOWFISHIES = "Poissons", -- Needs review
	SHOWFISHIES_INFO = "Affiche vos prises class\195\169es par type de poisson.",
	SHOWLOCATIONS = "Lieux",
	SHOWLOCATIONS_INFO = "Affiche vos prises class\195\169es par lieux.",
	SILVER_COIN = "Pi\195\169ce d'argent",
	STVZONENAME = "Vall\195\169e de Strangleronce",
	SWITCH_HELP = "|c#GREEN#/fb #SWITCH#|r#BRSPCS#Change l'\195\169quipement (si OutfitDisplayFrame ou Outfitter est charg\195\169)",
	TIMELEFT = "%s se termine dans %d:%02d",
	TIMETOGO = "%s commence dans %d:%02d",
	WATCHER_HELP = "|c#GREEN#/fb #WATCHER#|r [|c#GREEN##WATCHER_LOCK#|r or |c#GREEN##WATCHER_UNLOCK#|r or |c#GREEN##RESET#|r]#BRSPCS#D\195\169v\195\169rouille pour bouger la fen\195\170tre,#BRSPCS#lock pour arr\195\170ter, reset pour mettre a z\195\169ro",
	WEEKLY = "Hebdomadaire", -- Needs review
}
