if (select(2, UnitClass("player")) == "DEATHKNIGHT" and GetLocale() == "deDE" ) then
	CLCDK_ADDONNAME = "CLC DK"
	
	CLCDK_OPTIONS_SPEC_NONE = "Aktueller Spec: Nichts"
	CLCDK_OPTIONS_SPEC_UNHOLY = "Aktueller Spec: Unheilig"
	CLCDK_OPTIONS_SPEC_FROST = "Aktueller Spec: Frost"
	CLCDK_OPTIONS_SPEC_BLOOD = "Aktueller Spec: Blut"
	CLCDK_OPTIONS_RESET = "Standards wieder herstellen"
	CLCDK_OPTIONS_RESETLOCATION  = "Fensterpositionen zurück setzen"

	CLCDK_OPTIONS_FRAME = "Fenster Optionen"	
	CLCDK_OPTIONS_FRAME_GCD = "Zeige GCD Spirale" 
	CLCDK_OPTIONS_FRAME_CDS = "Show CD Spirals"
	CLCDK_OPTIONS_FRAME_RANGE = "Farbe abhängig von Entfernung"
	CLCDK_OPTIONS_FRAME_RUNE = "Zeige Runenleiste"
	CLCDK_OPTIONS_FRAME_RUNEBARS = "Show Graphical Runes"
	CLCDK_OPTIONS_FRAME_RUNE_O = "Runenreihenfolge"
	CLCDK_OPTIONS_FRAME_RUNE_ORDER = {
		"|cFFFF0000BB|r|cFF00FF00UU|r|cFF00FFFFFF|r", 
		"|cFFFF0000BB|r|cFF00FFFFFF|r|cFF00FF00UU|r", 
		"|cFF00FF00UU|r|cFFFF0000BB|r|cFF00FFFFFF|r", 
		"|cFF00FF00UU|r|cFF00FFFFFF|r|cFFFF0000BB|r", 
		"|cFF00FFFFFF|r|cFF00FF00UU|r|cFFFF0000BB|r", 
		"|cFF00FFFFFF|r|cFFFF0000BB|r|cFF00FF00UU|r"
	}
	CLCDK_OPTIONS_FRAME_RP = "Zeige Runenmacht"
	CLCDK_OPTIONS_FRAME_DISEASE = "Zeige Krankheitstimer"
	CLCDK_OPTIONS_FRAME_LOCKED = "CLC DK verschließen"
	CLCDK_OPTIONS_FRAME_LOCKEDPIECES = "Teile miteinander verbinden"
	CLCDK_OPTIONS_FRAME_VIEW = "Wähle wann CLC DK angezeigt werden soll"
	CLCDK_OPTIONS_FRAME_VIEW_NORM = "Normal"
	CLCDK_OPTIONS_FRAME_VIEW_TARGET = "Nur mit Ziel"
	CLCDK_OPTIONS_FRAME_VIEW_HIDE = "Immer verstecken"
	CLCDK_OPTIONS_FRAME_VIEW_SHOW = "Immer anzeigen"
	CLCDK_OPTIONS_FRAME_VIEW_NONE = "Nichts"
	CLCDK_OPTIONS_FRAME_SCALE = "Skalierung (0.5-5)"
	CLCDK_OPTIONS_FRAME_NORMALTRANS = "Trans. (0-1)"
	CLCDK_OPTIONS_FRAME_TRANS = "Transparenz des Hintergrundes(0-1)"
	CLCDK_OPTIONS_FRAME_COMBATTRANS = "Trans. im Kampf (0-1)"

	CLCDK_OPTIONS_CD = "Abklingzeiten Optionen"
	CLCDK_OPTIONS_CDR = "Rotation Optionen"
	CLCDK_OPTIONS_CDR_DISEASES_DD = "Optionen für Krankheiten"
	CLCDK_OPTIONS_CDR_DISEASES_DD_BOTH = "Beide Krankheiten(FF+BP)"
	CLCDK_OPTIONS_CDR_DISEASES_DD_ONE = "Nur eine Krankheit (FF)"
	CLCDK_OPTIONS_CDR_DISEASES_DD_NONE = "Ohne Krankheiten"	
	CLCDK_OPTIONS_CDR_ROTATION = "Verwende in der Rotation"
	CLCDK_OPTIONS_CDR_RP = "Runenmacht"
	CLCDK_OPTIONS_CDR_POOLINTERRUPT = "Runenmacht für Unterbrechung sammeln"
	CLCDK_OPTIONS_CDR_MOVEALT_INTERRUPT = "Zeige Unterbrechungssymbol"
	CLCDK_OPTIONS_CDR_MOVEALT_AOE = "Zeige AOE Symbol"
	CLCDK_OPTIONS_CDR_MOVEALT_DND = "Show DnD Icon"
	CLCDK_OPTIONS_CDR_PRIORITY = "Prioritätensymbol" 
	CLCDK_OPTIONS_CDR_CD1 = "Zeige linke Abklingzeiten"
	CLCDK_OPTIONS_CDR_CD2 = "Zeige rechte Abklingzeiten"
	CLCDK_OPTIONS_CDR_CD3 = "Zeige Äußerste Linke CoolDowns"
	CLCDK_OPTIONS_CDR_CD4 = "Zeige Äußerste Rechte CoolDowns"
	CLCDK_OPTIONS_CDR_CD_ONE = "Abklingzeit #1 zum Überwachen"
	CLCDK_OPTIONS_CDR_CD_TWO = "Abklingzeit #2 zum Überwachen"
	CLCDK_OPTIONS_CDR_CD_PRIORITY = "Priorität"
	CLCDK_OPTIONS_CDR_CD_PRESENCE = "Präsenz"
	CLCDK_OPTIONS_CDR_CD_SPEC = "Spec CDs/Buffs"
	CLCDK_OPTIONS_CDR_CD_NORMAL = "Normale CDs/Buffs"
	CLCDK_OPTIONS_CDR_CD_MOVES = "Moves"
	CLCDK_OPTIONS_CDR_CD_TIER = "Tier CDs/Buffs"
	CLCDK_OPTIONS_CDR_CD_TRINKETS = "Trinkets"
	CLCDK_OPTIONS_CDR_CD_TRINKETS_SLOT1 = "Trinket Slot 1"
	CLCDK_OPTIONS_CDR_CD_TRINKETS_SLOT2 = "Trinket Slot 2"
	CLCDK_OPTIONS_CDR_RACIAL = "Racial"
	
	CLCDK_OPTIONS_DT = "Optionen für Krankheitentracker"
	CLCDK_OPTIONS_DT_ENABLE = "Aktivieren"	
	CLCDK_OPTIONS_DT_CCOLOURS = "In Klassenfarben zeigen"
	CLCDK_OPTIONS_DT_TARGET = "Eigenes Ziel anzeigen"
	CLCDK_OPTIONS_DT_TCOLOURS = "Ziel und Fokus hervorheben"
	CLCDK_OPTIONS_DT_TPRIORITY = "Prioritize Target & Focus"
	CLCDK_OPTIONS_DT_GROWDOWN = "Nach unten wachsen"	
	CLCDK_OPTIONS_DT_COMBAT = "Kampflog überwachung abschalten"
	CLCDK_OPTIONS_DT_UPDATE = "Überwachungsverzögerung (0.1-10)"	
	CLCDK_OPTIONS_DT_NUMFRAMES = "Einheiten verfolgen (1-10)"
	CLCDK_OPTIONS_DT_WARNING = "Krankheitenwarnung (0-10sec)"
	CLCDK_OPTIONS_DT_THREAT = "Bedrohungsinformationen"
	CLCDK_OPTIONS_DT_THREAT_OFF = "Aus"
	CLCDK_OPTIONS_DT_THREAT_ANALOG = "Leisten"
	CLCDK_OPTIONS_DT_THREAT_DIGITAL = "Nur wenn auf Aggroliste"
	CLCDK_OPTIONS_DT_THREAT_HEALTH = "Show Health Bars"
	CLCDK_OPTIONS_DT_DOTS = "DOTs verfolgen"
	CLCDK_OPTIONS_DT_TRANS = "Trans. (0-1)"
	
	CLCDK_ABOUT = "Über"
	CLCDK_ABOUT_BODY = "Du hast Fragen? Vorschläge? Oder möchtest einfach mehr Informationen? <br/>Hinterlasse einen Kommentar auf Curse.com oder WoWInterface.com"
	CLCDK_ABOUT_GER = "Deutsche Übersetzung von Baine"
	CLCDK_ABOUT_CT = "Chinesische/Taiwanesische Übersetzung von yeah-chen"	
	CLCDK_ABOUT_AUTHOR = "Author: Threk - Illidan US"
	CLCDK_ABOUT_VERSION = "Version: ".. GetAddOnMetadata("CLC_DK", "Version")	
end