--[[ Credit for these translations goes to:
--]]

local L = LibStub("AceLocale-3.0"):NewLocale("TellMeWhen", "ptBR", false)
if not L then return end


L["Bleeding"] = "Sangrando" -- Needs review
L["BonusAgiStr"] = "Agi/Força aumentada" -- Needs review
L["BonusArmor"] = "Armadura aumentada" -- Needs review
L["BonusMana"] = "Mana aumentada" -- Needs review
L["BonusStamina"] = "Stamina aumentada" -- Needs review
L["BurstHaste"] = "Heroismo/Sede de Sangue" -- Needs review
L["BurstManaRegen"] = "Explosão de Regen de Mana" -- Needs review
L["CASTERFORM"] = "Forma Conjuradora" -- Needs review
L["CHAT_FRAME"] = "Janela de Chat" -- Needs review
L["CHOOSENAME_DIALOG"] = [=[Insira o Nome ou ID do que você quer que este ícone monitore. Você pode adicionar múltiplas entradas (qualquer combinação de nomes, IDs e equivalentes) separando-os com ponto e vírgulas (;).

Você pode clicar em habilidades/itens/links do chat com shift ou arrastar habilidades/itens para inserí-los nesta caixa de edição.]=]
L["CHOOSENAME_DIALOG_DDDEFAULT"] = "Conj. de Magias/Tipos de Dispell" -- Needs review
L["CHOOSENAME_DIALOG_PETABILITIES"] = "|cFFFF5959HABILIDADES DE PETS|r devem usar o ID da habilidade. "
L["CHOOSENAME_EQUIVS_TOOLTIP"] = "Você pode escolher conjuntos de buffs, debuffs, magias conjuradas, retornos dimimuidos ou tipos de dispell (Magica, Maldição, etc.) predefinidos desse menu para inserir no quadro de \"%s\"." -- Needs review
L["CMD_OPTIONS"] = "Opções"
L["CONDITIONPANEL_ALIVE"] = "Unidade está Viva" -- Needs review
L["CONDITIONPANEL_AND"] = "E"
L["CONDITIONPANEL_ANDOR"] = "E / Ou"
L["CONDITIONPANEL_COMBO"] = "Pontos de Combo" -- Needs review
L["CONDITIONPANEL_ECLIPSE_DESC"] = "Eclipse tem um alcance de -100 (eclipse lunar) até 100 (eclipse solar). Insira -80 se quiser que o ícone apareça com um valor de 80 poder lunar." -- Needs review
L["CONDITIONPANEL_EQUALS"] = "Igual a"
L["CONDITIONPANEL_GREATER"] = "Maior Que"
L["CONDITIONPANEL_GREATEREQUAL"] = "Maior ou Igual a"
L["CONDITIONPANEL_ICON"] = "Ícone Mostrado" -- Needs review
L["CONDITIONPANEL_ICON_DESC"] = [=[A condição será verdadeira se o ícone especificado for mostrado com um alpha acima de 0 ou escondido com alpha de 0 se definido como falso.

Se você não quiser mostrar os ícones que estão sendo checados, cheque %q no editor de ícones checados.

O grupo do ícone checado deverá também ser mostrado em ordem para checar o ícone, mesmo se a condição for definida como falsa.]=] -- Needs review
L["CONDITIONPANEL_LESS"] = "Menor Que"
L["CONDITIONPANEL_LESSEQUAL"] = "Menor ou Igual a"
L["CONDITIONPANEL_NOTEQUAL"] = "Diferente de"
L["CONDITIONPANEL_OPERATOR"] = "Operador"
L["CONDITIONPANEL_OR"] = "Ou"
L["CONDITIONPANEL_POWER"] = "Recurso Principal"
L["CONDITIONPANEL_POWER_DESC"] = "Vai checar a energia se a unidade for um druida em forma de felino, raiva se for um guerreiro, etc." -- Needs review
L["CONDITIONPANEL_TYPE"] = "Tipo"
L["CONDITIONPANEL_UNIT"] = "Unidade" -- Needs review
L["CONDITIONPANEL_VALUEN"] = "Valor" -- Needs review
L["Disarmed"] = "Desarmado" -- Needs review
L["Disoriented"] = "Desorientado" -- Needs review
L["ECLIPSE_DIRECTION"] = "Direção do Eclipse" -- Needs review
L["GCD_ACTIVE"] = "GCD ativo" -- Needs review
L["GROUPICON"] = "Grupo: %s, Ícone: %s" -- Needs review
L["ICONALPHAPANEL_FAKEHIDDEN"] = "Sempre Esconder" -- Needs review
L["ICONALPHAPANEL_FAKEHIDDEN_DESC"] = "Causa que o ícone seja escondido o tempo todo, mas ativado para permitir as condições dos outros ícones a checar este icone ou para os ícones meta incluírem este ícone." -- Needs review
L["ICONMENU_ABSENT"] = "Ausente"
L["ICONMENU_ALPHA"] = "Opacidade" -- Needs review
L["ICONMENU_ALWAYS"] = "Sempre"
L["ICONMENU_BUFF"] = "Buff"
L["ICONMENU_BUFFDEBUFF"] = "Buff/Debuff"
L["ICONMENU_BUFFTYPE"] = "Buff ou debuff" -- Needs review
L["ICONMENU_CHOOSENAME"] = "Escolha os nome(s)/ID(s) para checar"
L["ICONMENU_COOLDOWNCHECK"] = "Checagem de Cooldown" -- Needs review
L["ICONMENU_COOLDOWNTYPE"] = "Tipo de Cooldown"
L["ICONMENU_DEBUFF"] = "Debuff"
L["ICONMENU_ENABLE"] = "Habilitado"
L["ICONMENU_FOCUS"] = "Foco"
L["ICONMENU_FOCUSTARGET"] = "Alvo do foco"
L["ICONMENU_FRIEND"] = "Amigável"
L["ICONMENU_HOSTILE"] = "Hostil"
L["ICONMENU_IGNORENOMANA"] = "Ignorar perda de força" -- Needs review
L["ICONMENU_INVERTBARS"] = "Preencher barras" -- Needs review
L["ICONMENU_MANACHECK"] = "Checar poder" -- Needs review
L["ICONMENU_ONLYMINE"] = "Mostrar somente o meu" -- Needs review
L["ICONMENU_PETTARGET"] = "Alvo do Pet"
L["ICONMENU_PRESENT"] = "Presente"
L["ICONMENU_RANGECHECK"] = "Verificação de alcance" -- Needs review
L["ICONMENU_REACT"] = "Reação da Unidade" -- Needs review
L["ICONMENU_REACTIVE"] = "Habilidade Reativa" -- Needs review
L["ICONMENU_SHOWTIMER"] = "Mostrar o tempo"
L["ICONMENU_SHOWTIMERTEXT"] = "Mostrar texto de contagem" -- Needs review
L["ICONMENU_SHOWTIMERTEXT_DESC"] = "Marque esta opção para mostrar em texto o cooldown/duração restante no ícone." -- Needs review
L["ICONMENU_SHOWWHEN"] = "Mostrar ícone quando"
L["ICONMENU_SPELL"] = "Magia ou habilidade" -- Needs review
L["ICONMENU_STACKS_MAX_DESC"] = "Número máximo de stacks permitidos a mostrar o ícone" -- Needs review
L["ICONMENU_STACKS_MIN_DESC"] = "Número mínimo de stacks necessários para mostrar o ícone" -- Needs review
L["ICONMENU_TARGETTARGET"] = "Alvo do alvo"
L["ICONMENU_TOTEM"] = "Totem"
L["ICONMENU_TYPE"] = "Tipo do ícone"
L["ICONMENU_UNUSABLE"] = "Inutilizável"
L["ICONMENU_USABLE"] = "Utilizável"
L["ICONMENU_VEHICLE"] = "Veículo" -- Needs review
L["ICONMENU_WPNENCHANT"] = "Encantamento da Arma"
L["ICONMENU_WPNENCHANTTYPE"] = "Slot de arma a ser monitorado" -- Needs review
L["ICONTOCHECK"] = "Ícone a marcar" -- Needs review
L["ICON_TOOLTIP1"] = "TellMeWhen"
L["ImmuneToMagicCC"] = "Imune a Mágica de Controle (CC)" -- Needs review
L["ImmuneToStun"] = "Imune a Atordoamento" -- Needs review
L["Incapacitated"] = "Incapacitado" -- Needs review
L["IncreasedAP"] = "Poder de Ataque aumentado" -- Needs review
L["IncreasedCrit"] = "Chance de Crítico aumentada" -- Needs review
L["IncreasedDamage"] = "Dano Realizado aumentado" -- Needs review
L["IncreasedPhysHaste"] = "Aceleração física aumentada" -- Needs review
L["IncreasedSpellHaste"] = "Aceleração de magia aumentado" -- Needs review
L["IncreasedSPsix"] = "Poder mágico aumentado (6%)" -- Needs review
L["IncreasedSPten"] = "Poder mágico aumentado (10%)" -- Needs review
L["IncreasedStats"] = "Stats aumentados" -- Needs review
L["ManaRegen"] = "Recuperação de Mana aumentado"
L["MOON"] = "Lua" -- Needs review
L["MOUSEOVER_TOKEN_NOT_FOUND"] = "<no mouseover>" -- Needs review
L["NONE"] = "Nenhum" -- Needs review
L["OUTLINE_NO"] = "Sem Contorno" -- Needs review
L["OUTLINE_THICK"] = "Contorno Grosso" -- Needs review
L["OUTLINE_THIN"] = "Contorno Fino" -- Needs review
L["PhysicalDmgTaken"] = "Dano Físico Levado" -- Needs review
L["PushbackResistance"] = "Resistência a Pushback aumentada" -- Needs review
L["ReducedArmor"] = "Armadura Reduzida" -- Needs review
L["ReducedAttackSpeed"] = "Velocidade de Ataque Reduzida"
L["ReducedCastingSpeed"] = "Velocidade de Conj. Reduzida" -- Needs review
L["ReducedHealing"] = "Cura Reduzida"
L["ReducedPhysicalDone"] = "Dano Físico Causado Reduzido" -- Needs review
L["Resistances"] = "Resistência Mágica Aumentada"
L["RESIZE"] = "Redimensionar"
L["RESIZE_TOOLTIP"] = "Clique e arraste para mudar o tamanho"
L["Rooted"] = "Enraizado" -- Needs review
L["Silenced"] = "Silenciado" -- Needs review
L["SpellCritTaken"] = "Magia Crít. Levada Aumentada" -- Needs review
L["SpellDamageTaken"] = "Dano de Magia Levado Aumentado" -- Needs review
L["Stunned"] = "Atordoado" -- Needs review
L["SUG_MATCH_WPNENCH_ENCH"] = "Arma ?d?[ae]? (.*)" -- Needs review
L["SUG_PATTERNMATCH_FISHINGLURE"] = "Isca de Pesca %(%+%d+ Pesca%)"
L["SUG_PATTERNMATCH_SHARPENINGSTONE"] = "Afiado %(%+%d+ Dano%)"
L["SUG_PATTERNMATCH_WEIGHTSTONE"] = "Pesado %(%+%d+ Dano%)"
L["SUN"] = "Sol" -- Needs review
L["UIPANEL_ALLRESET"] = "Redefinir tudo"
L["UIPANEL_BARIGNOREGCD"] = "Barras Ignoram GCD" -- Needs review
L["UIPANEL_BARIGNOREGCD_DESC"] = "Se marcado, as barras de cooldown não irão mudar de valor se o cooldown ativado for um cooldown global." -- Needs review
L["UIPANEL_BARTEXTURE"] = "Textura da Barra"
L["UIPANEL_CLOCKIGNOREGCD"] = "Timers Ignoram GCD" -- Needs review
L["UIPANEL_CLOCKIGNOREGCD_DESC"] = "Se marcado, os timers e os relógios de cooldown não irão ativar de um cooldown global." -- Needs review
L["UIPANEL_COLOR_ABSENT"] = "Cor ausente" -- Needs review
L["UIPANEL_COLOR_ABSENT_DESC"] = "A cor do ícone quando o buff/debuff/encantamento/totem estiver faltando e o ícone estiver definido para sempre ser mostrado." -- Needs review
L["UIPANEL_COLOR_COMPLETE"] = "CD/Duração Completa" -- Needs review
L["UIPANEL_COLOR_COMPLETE_DESC"] = "Cor da barra de overlay de cooldown/duração quando o cooldown/duração estiver completo" -- Needs review
L["UIPANEL_COLOR_DESC"] = "As opções a seguir apenas afetam as cores dos ícones quando eles estiverem definidos para sempre serem mostrados." -- Needs review
L["UIPANEL_COLOR_OOM"] = "Cor de falta de poder" -- Needs review
L["UIPANEL_COLOR_OOR"] = "Cor da falta de alcance" -- Needs review
L["UIPANEL_COLOR_PRESENT"] = "Cor presente" -- Needs review
L["UIPANEL_COLOR_PRESENT_DESC"] = "O tom do ícone quando o buff/debuff/encantamento/totem estiver presente e o ícone estiver marcado para sempre ser mostrado." -- Needs review
L["UIPANEL_COLORS"] = "Cores" -- Needs review
L["UIPANEL_COLUMNS"] = "Colunas"
L["UIPANEL_ENABLEGROUP"] = "Habilitar Grupo"
L["UIPANEL_GROUPRESET"] = "Redefinir Posição"
L["UIPANEL_GROUPS"] = "Grupos" -- Needs review
L["UIPANEL_ICONSPACING"] = "Espaçamento de Ícone" -- Needs review
L["UIPANEL_LOCK"] = "Trancar Grupo" -- Needs review
L["UIPANEL_LOCKUNLOCK"] = "Trancar/Destrancar AddOn"
L["UIPANEL_MAINOPT"] = "Opções Principais" -- Needs review
L["UIPANEL_ONLYINCOMBAT"] = "Mostrar somente em combate" -- Needs review
L["UIPANEL_PRIMARYSPEC"] = "Especialização Primária" -- Needs review
L["UIPANEL_ROWS"] = "Linhas" -- Needs review
L["UIPANEL_SECONDARYSPEC"] = "Especialização Secundária" -- Needs review
L["UIPANEL_SUBTEXT2"] = "Ícones funcionam quando trancados. Quando destrancados, você pode mover/redimensionar grupos e clicar com o botão direito em ícones individualmente para mais configurações. Você também pode digitar /tellmewhen ou /tmw para travar/destravar." -- Needs review
L["UIPANEL_TOOLTIP_ALLRESET"] = "Redefinir DADOS e POSIÇÃO para todos os ícones e grupos, assim como qualquer outra configuração. " -- Needs review
L["UIPANEL_TOOLTIP_COLUMNS"] = "Definir o número de colunas neste grupo" -- Needs review
L["UIPANEL_TOOLTIP_ENABLEGROUP"] = "Mostrar e habilitar este grupo" -- Needs review
L["UIPANEL_TOOLTIP_GROUPRESET"] = "Redefinir a posição e escala deste grupo" -- Needs review
L["UIPANEL_TOOLTIP_ONLYINCOMBAT"] = "Marque para que este grupo só seja mostrado em combate" -- Needs review
L["UIPANEL_TOOLTIP_PRIMARYSPEC"] = "Marque para mostrar este grupo enquanto sua especialização primária estiver ativa" -- Needs review
L["UIPANEL_TOOLTIP_ROWS"] = "Define o número de linhas neste grupo" -- Needs review
L["UIPANEL_TOOLTIP_SECONDARYSPEC"] = "Marque para mostrar este grupo enquanto sua especiação secundária estiver ativa" -- Needs review
L["UIPANEL_TOOLTIP_UPDATEINTERVAL"] = "Define o quão frequente (em segundos) os ícones são verificados para mostrar/esconder, alfa, condições, etc. Zero é o mais rápido possível. Valores menores podem ter um impacto significativo no número de quadros por segundo em computadores mais fracos" -- Needs review
L["UIPANEL_UPDATEINTERVAL"] = "Intervalo de Atualização" -- Needs review
