--[[ Credit for these translations goes to:
	TomHB
	fiesekeule
	Quevain
	XNuclearWinterX
	erwinmeier
	xevilgrin
	Farronski
--]]
local L = LibStub("AceLocale-3.0"):NewLocale("TellMeWhen", "deDE", false)
if not L then return end


L["AIR"] = "Luft" -- Needs review
L["ALLOWVERSIONWARN"] = "Melde neue Version" -- Needs review
L["ASPECT"] = "Aspekt" -- Needs review
L["AURA"] = "Aura" -- Needs review
L["BleedDamageTaken"] = "Erhöhter Schaden durch Blutungseffekte"
L["Bleeding"] = "Blutend" -- Needs review
L["BonusAgiStr"] = "Erhöhte Beweglichkeit/Stärke"
L["BonusArmor"] = "Erhöhte Rüstung"
L["BonusMana"] = "Erhöhter Manavorrat"
L["BonusStamina"] = "Erhöhte Ausdauer" -- Needs review
L["BOTTOM"] = "unten"
L["BOTTOMLEFT"] = "unten links"
L["BOTTOMRIGHT"] = "unten rechts"
L["BurstHaste"] = "Heldentum/Blutrausch" -- Needs review
L["BurstManaRegen"] = "Stark erhöhte Mana Regeneration" -- Needs review
L["CASTERFORM"] = "Zaubergestalt"
L["CENTER"] = "mittig"
L["CHOOSENAME_DIALOG"] = "Geben Sie Namen oder ID des Zaubers / Gegenstands / Buffs / Debuffs / der Fähigkeit ein, die mit diesem Symbol überwacht werden soll. Sie können mehrere Buffs / Debuffs hinzufügen, indem Sie diese mit ';' trennen (ausgenommen Abklingzeiten mit mehreren Variablen)." -- Needs review
L["CHOOSENAME_DIALOG_DDDEFAULT"] = "Vordefinierte Zauber-Sätze"
L["CHOOSENAME_DIALOG_PETABILITIES"] = "Begleiterfähigkeiten müssen per ID eingetragen werden!" -- Needs review
L["CHOOSENAME_EQUIVS_TOOLTIP"] = "Du kannst einen vordefinierten Satz von Buffs/Debuffs in diesem Menü festlegen." -- Needs review
L["CMD_OPTIONS"] = "Optionen"
L["CNDTCAT_ATTRIBUTES_PLAYER"] = "Spieler-Attribute" -- Needs review
L["CNDTCAT_ATTRIBUTES_UNIT"] = "Einheiten-Attribute" -- Needs review
L["COLOR_CBC"] = "Abklingzeit-Leiste - Ende" -- Needs review
L["COLOR_CBC_DESC"] = "Farbe der Abklingzeit/Restdauer overlay-Leiste, wenn die Abklingzeit/Restdauer beendet ist." -- Needs review
L["COLOR_CBS"] = "Abklingzeit-Leiste - Beginn" -- Needs review
L["COLOR_COA"] = "Zählend, Timer deaktiviert, immer sichtbar" -- Needs review
L["COLOR_COLOR"] = "Farbe" -- Needs review
L["COLOR_COS"] = "Zählend, Timer deaktiviert, manchmal sichtbar" -- Needs review
L["COLOR_CTA"] = "Zählend, Timer aktiviert, immer sichtbar" -- Needs review
L["COLOR_CTS"] = "Zählend, Timer aktiviert, manchmal sichtbar" -- Needs review
L["COLOR_DEFAULT"] = "*Globale Farben*" -- Needs review
L["COLOR_DESATURATE"] = "Grau" -- Needs review
L["COLOR_DESATURATE_DESC"] = "Bestätigen Sie dies um das Symbol zu entfärben, wenn diese Farbe genutzt wird. Dies wird alle Farben entfernen und das Symbol Schwarz/Weiß machen." -- Needs review
L["COLOR_NA"] = "Beendet, immer sichtbar" -- Needs review
L["COLOR_NS"] = "Beendet, manchmal sichtbar" -- Needs review
L["COLOR_OOM"] = "niedriges Mana" -- Needs review
L["COLOR_OOM_DESC"] = "Farbe des Symbols, wenn Sie nicht über die Ressourcen verfügen um eine Fähigkeit zu nutzen." -- Needs review
L["COLOR_OOR"] = "Außer Reichweite" -- Needs review
L["COLOR_OOR_DESC"] = "Farbe des Symbols, wenn Sie außerhalb der Reichweite sind um eine Fähigkeit zu nutzen." -- Needs review
L["COLOR_OORM"] = "Außer Reichweite & Mana" -- Needs review
L["COLOR_OORM_DESC"] = "Farbe des Symbols, wenn Sie nicht über die Ressourcen verfügen und außerhalb der Reichweite sind um eine Fähigkeit zu nutzen." -- Needs review
L["COLOR_OVERRIDEDEFAULT"] = "Verwendungszweck" -- Needs review
L["COLOR_OVERRIDEDEFAULT_DESC"] = "Bestätigen Sie dies um die *Globale Farben* Einstellungen zu überschreiben und stattdessen diese Einstellungen zu nutzen." -- Needs review
L["COLOR_RESET_DESC"] = "Setzt diese Einstellungen zu ihren Standardwerten zurück." -- Needs review
L["CONDITIONALPHA_CONDITIONICON"] = "unpassende Dauer" -- Needs review
L["CONDITIONALPHA_CONDITIONICON_DESC"] = "Dies wird verwendet, falls die Anforderungen an die Dauer nicht erreicht werden. Diese Einstellung wird ignoriert, falls das Icon bereits von den beiden anderen Unsichtsbarkeitseinstellungen verdeckt wird." -- Needs review
L["CONDITIONPANEL_ALIVE"] = "Einheit ist lebendig"
L["CONDITIONPANEL_ALIVE_DESC"] = "Die Bedingung wird erfüllt, wenn die spezifizierte Einheit lebt."
L["CONDITIONPANEL_AND"] = "und"
L["CONDITIONPANEL_ANDOR"] = "und / oder"
L["CONDITIONPANEL_CLASSIFICATION"] = "Einheit Klassifizierung" -- Needs review
L["CONDITIONPANEL_COMBAT"] = "Einheit im Kampf"
L["CONDITIONPANEL_COMBO"] = "Kombo Punkte"
L["CONDITIONPANEL_ECLIPSE_DESC"] = [=[Finsternis hat eine Reichweite von -100 (Mondfinsternis) bis 100 (Sonnenfinsternis)
Gib -80 ein wenn du möchtest das das Symbol mit einem Wert von 80 Mond-Macht funktioniert. ]=]
L["CONDITIONPANEL_EQUALS"] = "gleich"
L["CONDITIONPANEL_EXISTS"] = "Einheit existiert"
L["CONDITIONPANEL_GREATER"] = "größer als"
L["CONDITIONPANEL_GREATEREQUAL"] = "größer als oder gleich"
L["CONDITIONPANEL_ICON"] = "Zeige Symbol"
L["CONDITIONPANEL_ICON_DESC"] = "Die Bedingung wird erfüllt, wenn das Symbol derzeit mit einer Transparenz von über 0 angezeigt oder versteckt mit einer Transparenz von 0 wird." -- Needs review
L["CONDITIONPANEL_ICON_HIDDEN"] = "Versteckt" -- Needs review
L["CONDITIONPANEL_ICON_SHOWN"] = "Gezeigt" -- Needs review
L["CONDITIONPANEL_LESS"] = "kleiner als"
L["CONDITIONPANEL_LESSEQUAL"] = "kleiner als oder gleich"
L["CONDITIONPANEL_NAMETOOLTIP"] = "unterteile verschieden Namen mit Semikolons (;)" -- Needs review
L["CONDITIONPANEL_NOTEQUAL"] = "ungleich"
L["CONDITIONPANEL_OPERATOR"] = "Operator"
L["CONDITIONPANEL_OR"] = "oder"
L["CONDITIONPANEL_POWER"] = "Primäre Ressource"
L["CONDITIONPANEL_POWER_DESC"] = [=[Prüft auf Energie, falls die Einheit ein Druide in Katzengestalt ist,
auf Wut, wenn die Einheit ein Krieger ist, usw.]=]
L["CONDITIONPANEL_TYPE"] = "Typ"
L["CONDITIONPANEL_UNIT"] = "Einheit"
L["CONDITIONPANEL_VALUEN"] = "Wert"
L["CONDITIONPANEL_VEHICLE"] = "Einheit kontrolliert Fahrzeug" -- Needs review
L["CrowdControl"] = "Massen-Kontrolle"
L["Curse"] = "Fluch"
L["DISABLED"] = "Deaktiviert"
L["Disarmed"] = "Entwaffnet"
L["Disease"] = "Krankheit"
L["Disoriented"] = "Verwirrt"
L["DR-MindControl"] = "Gedankenkontrolle" -- Needs review
L["DURATIONPANEL_TITLE"] = "Wirkungszeit"
L["EARTH"] = "Erde" -- Needs review
L["ECLIPSE_DIRECTION"] = "Finsternis Richtung"
L["elite"] = "Elite"
L["ENABLINGOPT"] = "TellMeWhen_Options ist deaktiviert. Aktiviere..." -- Needs review
L["EVENTS_SETTINGS_GLOBAL_DESC"] = "Beachten Sie, dass Ereignis-Einstellungen das Ereignis für alle outputs, inklusive Ton und Text, beeinflussen." -- Needs review
L["EVENTS_SETTINGS_HEADER"] = "Ereignis-Einstellungen" -- Needs review
L["EVENTS_SETTINGS_ONLYSHOWN"] = "Nur nutzen, wenn das Icon sichtbar ist." -- Needs review
L["EVENTS_SETTINGS_ONLYSHOWN_DESC"] = "Das Bestätigen dieser Einstellung wird das Ereignis daran hindern jegliche verknüpften Handlungen auszuführen, sollte das Icon nicht sichtbar sein." -- Needs review
L["FALSE"] = "Falsch"
L["Feared"] = "Furcht"
L["fGROUP"] = "Gruppe %s" -- Needs review
L["fICON"] = "Icon %s" -- Needs review
L["FIRE"] = "Feuer" -- Needs review
L["FONTCOLOR"] = "Schriftfarbe"
L["FONTSIZE"] = "Schriftgröße"
L["GROUPADDONSETTINGS"] = "Gruppeneinstellungen" -- Needs review
L["GROUPCONDITIONS"] = "Gruppenbedingungen" -- Needs review
L["GROUPICON"] = "Gruppe: %s, Symbol %d"
L["Heals"] = "Spieler Heilungen"
L["ICONALPHAPANEL_FAKEHIDDEN"] = "Versteckt"
L["ICONALPHAPANEL_FAKEHIDDEN_DESC"] = "Macht das Symbol unsichtbar, lässt es aber aktiv damit andere Symbole, verknüpfte Bedingungen weiterhin prüfen können." -- Needs review
L["ICONMENU_ABSENT"] = "Abwesend"
L["ICONMENU_ALPHA"] = "Transparenz"
L["ICONMENU_ALWAYS"] = "Immer"
L["ICONMENU_ANCHORTO_UIPARENT"] = "Anker zurücksetzen" -- Needs review
L["ICONMENU_BOTH"] = "Entweder"
L["ICONMENU_BUFF"] = "Buff"
L["ICONMENU_BUFFDEBUFF"] = "Buff / Debuff"
L["ICONMENU_BUFFDEBUFF_DESC"] = "Prüft Buffs und/oder Debuffs." -- Needs review
L["ICONMENU_BUFFTYPE"] = "Buff oder Debuff" -- Needs review
L["ICONMENU_CAST"] = "Zauber"
L["ICONMENU_CAST_DESC"] = "Prüft gewirkte und kanalisierte Zauber." -- Needs review
L["ICONMENU_CASTS"] = "Zaubersprüche"
L["ICONMENU_CHOOSENAME"] = "Wähle Zauber / Gegenstand / Buff / etc."
L["ICONMENU_CHOOSENAME_WPNENCH"] = "Wählen Sie eine oder mehrere Verzauberungen zum Prüfen." -- Needs review
L["ICONMENU_COOLDOWNCHECK"] = "Abklingzeiten aktiviert?"
L["ICONMENU_COOLDOWNCHECK_DESC"] = "Aktivieren für Farbänderung des Symbols, wenn reaktive Fähigkeit auf Abklingzeit ist."
L["ICONMENU_COOLDOWNTYPE"] = "Abklingzeit Typ"
L["ICONMENU_COPYHERE"] = "hierher kopieren" -- Needs review
L["ICONMENU_DEBUFF"] = "Debuff"
L["ICONMENU_DISPEL"] = "Entfernen-Typ"
L["ICONMENU_DURATION_MAX_DESC"] = "Maximale Wirkungszeit erlaubt das Symbol anzuzeigen."
L["ICONMENU_DURATION_MIN_DESC"] = "Minimum Wirkungszeit benötigt um das Symbol anzuzeigen"
L["ICONMENU_ENABLE"] = "Aktiviert"
L["ICONMENU_FOCUS"] = "Fokus"
L["ICONMENU_FOCUSTARGET"] = "Fokusziel"
L["ICONMENU_FRIEND"] = "freundliche Einheiten"
L["ICONMENU_HIDEUNEQUIPPED"] = "Verstecken wenn der Platz leer ist."
L["ICONMENU_HOSTILE"] = "feindliche Einheiten"
L["ICONMENU_IGNORERUNES"] = "Ignoriere Runen"
L["ICONMENU_IGNORERUNES_DESC_DISABLED"] = "Du musst die \"Cooldown Überprüfung\" Einstellung wählen, um \"Runen ignorieren\" einzuschalten." -- Needs review
L["ICONMENU_INVERTBARS"] = "Leisten auffüllen"
L["ICONMENU_ITEMCOOLDOWN"] = "Item Abklingzeit" -- Needs review
L["ICONMENU_ITEMCOOLDOWN_DESC"] = "Prüft die Abklingzeit von Items." -- Needs review
L["ICONMENU_MANACHECK"] = "Ressourcen Prüfung?"
L["ICONMENU_MANACHECK_DESC"] = "Aktivieren für Farbänderung des Symbols, wenn kein/e Mana/Wut/Runenmacht/etc. vorhanden ist."
L["ICONMENU_META"] = "Meta Symbol"
L["ICONMENU_META_DESC"] = [=[Dieser Symbol Typ kann dazu genutzt werden um mehrere Symbole, in einem einzigen, zu kombinieren.
Icons that have fake hidden enabled will still be shown if they would otherwise be shown.]=] -- Needs review
L["ICONMENU_MOUSEOVER"] = "Mausover"
L["ICONMENU_MOUSEOVERTARGET"] = "Mausover des Ziels"
L["ICONMENU_MOVEHERE"] = "hierher verschieben" -- Needs review
L["ICONMENU_MULTISTATECD_DESC"] = [=[Dieses Symbol sollte verwendet werden, wenn du dir mehrere Status / Texturen / etc. von einer Abklingzeit anzeigen lassen willst.
Einige Beispiele sind: Segenswort: Züchtigung, Dunkles Simulakrum, Verstohlenheit und Aspekte / Auren / Gestaltveränderungen.
WICHTIG: Der Zauber MUSS auf einer deiner Aktionsleisten liegen!
Du solltest außerdem sicherstellen, dass die Fähigkeit in ihrem Standard Zustand ist beim Verlassen der TMW Config.]=] -- Needs review
L["ICONMENU_ONLYEQPPD"] = "nur wenn ausgerüstet" -- Needs review
L["ICONMENU_ONLYIFCOUNTING"] = "Anzeige nur bei aktiviertem Timer." -- Needs review
L["ICONMENU_ONLYINTERRUPTIBLE"] = "Nur unterbrechbare Zauber"
L["ICONMENU_ONLYMINE"] = "Nur zeigen, wenn selbst gezaubert" -- Needs review
L["ICONMENU_PETTARGET"] = "Begleiterziel"
L["ICONMENU_PRESENT"] = "Vorhanden"
L["ICONMENU_RANGECHECK"] = "Reichweiten Prüfung"
L["ICONMENU_RANGECHECK_DESC"] = "Aktivieren für Farbänderung des Symbols wenn ausser Reichweite."
L["ICONMENU_REACT"] = "Einheit Reaktion"
L["ICONMENU_REACTIVE"] = "Reaktiver Zauber oder Fähigkeit"
L["ICONMENU_RUNES_DESC"] = "Prüft Runen-Abklingzeiten" -- Needs review
L["ICONMENU_SHOWTIMER"] = "Zeige Timer"
L["ICONMENU_SHOWTIMERTEXT"] = "Zeige Timertext" -- Needs review
L["ICONMENU_SHOWTIMERTEXT_DESC"] = "Nur wirksam wenn 'Zeige Timer' aktiviert ist. Benötigt das AddOn 'OmniCC'" -- Needs review
L["ICONMENU_SHOWWHEN"] = "Zeige Symbol, wenn"
L["ICONMENU_SORTASC"] = "Niedrige Dauer" -- Needs review
L["ICONMENU_SORTASC_DESC"] = "Bestätigen Sie dieses Feld um Zaubersprüche mit der niedrigsten Dauer zu priorisieren." -- Needs review
L["ICONMENU_SORTDESC"] = "Hohe Dauer" -- Needs review
L["ICONMENU_SORTDESC_DESC"] = "Bestätigen Sie dieses Feld um Zaubersprüche mit der höchsten Dauer zu priorisieren." -- Needs review
L["ICONMENU_SPELL"] = "Zauber oder Fähigkeit"
L["ICONMENU_SPELLCOOLDOWN"] = "Zauberspruch Abklingzeit" -- Needs review
L["ICONMENU_SPELLCOOLDOWN_DESC"] = "Prüft die Abklingzeit von Zaubersprüchen in Ihrem Zauberbuch." -- Needs review
L["ICONMENU_SPLIT"] = "In neue Gruppe aufteilen" -- Needs review
L["ICONMENU_SPLIT_DESC"] = "Erstellen Sie eine neue Gruppe und bewegen Sie dieses Symbol in diese hinein. Viele Gruppeneinstellungen werden auf die neue Gruppe übertragen werden." -- Needs review
L["ICONMENU_STACKS_MAX_DESC"] = "Maximale Anzahl Stapel der Aura erlaubt, um das Symbol anzuzeigen." -- Needs review
L["ICONMENU_STACKS_MIN_DESC"] = "Minimale Anzahl Stapel der Aura benötigt, um das Symbol anzuzeigen." -- Needs review
L["ICONMENU_TARGETTARGET"] = "Ziel des Ziels"
L["ICONMENU_TOTEM"] = "Totem / non-MoG Ghoul"
L["ICONMENU_TOTEM_DESC"] = "Prüft Ihre Totems." -- Needs review
L["ICONMENU_TYPE"] = "Icon Typ"
L["ICONMENU_UNUSABLE"] = "unbenutzbar"
L["ICONMENU_USABLE"] = "Benutzbar"
L["ICONMENU_VEHICLE"] = "Fahrzeug"
L["ICONMENU_WPNENCHANT"] = "Temporäre Waffenverzauberung"
L["ICONMENU_WPNENCHANTTYPE"] = "zu überwachender Waffenplatz"
L["ICONTOCHECK"] = "Zu prüfendes Symbol"
L["ICON_TOOLTIP1"] = "TellMeWhen"
L["ImmuneToMagicCC"] = "Immun gegen magische Beherrschung"
L["ImmuneToStun"] = "Immun gegen Betäubungseffekte" -- Needs review
L["IMPORTERROR_FAILEDPARSE"] = "Es gab einen Fehler beim Auslesen des Strings. Überprüfe, ob der vollständige String von der Quelle kopiert wurde." -- Needs review
L["IMPORT_FROMCOMM"] = "Von Spieler" -- Needs review
L["IMPORT_FROMCOMM_DESC"] = "Wenn ein weiterer Benutzer von TellMeWhen Ihnen Konfigurationsdaten schickt, können Sie diese von diesem Untermenü importieren." -- Needs review
L["IMPORT_FROMLOCAL"] = "Von Profil" -- Needs review
L["IMPORT_FROMSTRING"] = "Von String (Zeichenkette)" -- Needs review
L["IMPORT_FROMSTRING_DESC"] = "Um einen String zu importieren, drücken Sie STRG+V um den String einzufügen, nachdem Sie es mit STRG-C kopiert haben. Navigieren Sie danach zurück zu diesem Untermenü." -- Needs review
L["IMPORT_FROMSTRING_ERR_NOICONS"] = "Nutzen Sie den Icon-Editor um Icons zu importieren." -- Needs review
L["IMPORT_HEADING"] = "Import" -- Needs review
L["IMPORT_PROFILE"] = "Profil kopieren" -- Needs review
L["IMPORT_PROFILE_NEW"] = "Neues Profil erstellen" -- Needs review
L["Incapacitated"] = "Bewegungsunfähig"
L["IncreasedAP"] = "Erhöht Angriffskraft"
L["IncreasedCrit"] = "Erhöht Chance Kritisch zu treffen"
L["IncreasedDamage"] = "Erhöhter verursachter Schaden"
L["IncreasedPhysHaste"] = "Erhöhtes Nahkampfangriffstempo" -- Needs review
L["IncreasedSpellHaste"] = "Erhöhtes Zaubertempo"
L["IncreasedSPsix"] = "Erhöhte Zaubermacht (6%)"
L["IncreasedSPten"] = "Erhöhte Zaubermacht (10%)"
L["IncreasedStats"] = "Erhöhte Attribute"
L["ITEMCOOLDOWN"] = "Item Abklingzeit" -- Needs review
L["LDB_TOOLTIP1"] = "|cff7fffffLinks-Klick|r um die Gruppen umzuschalten."
L["LDB_TOOLTIP2"] = "|cff7fffffRechts klick|r um spezielle Gruppen ein/auszublenden."
L["LEFT"] = "links"
L["LOCKED"] = "gesperrt"
L["Magic"] = "Magie"
L["!!Main Addon Description"] = "Bietet visuelle, akustische und schriftliche Benachrichtigungen über Cooldowns, Buffs and so ziemlich alles andere."
L["ManaRegen"] = "Erhöhte Manaregeneration"
L["METAPANEL_DOWN"] = "nach unten bewegen" -- Needs review
L["METAPANEL_INSERT"] = "Ein Icon einfügen" -- Needs review
L["METAPANEL_REMOVE"] = "Dieses Icon entfernen" -- Needs review
L["METAPANEL_UP"] = "nach oben bewegen" -- Needs review
L["MOON"] = "Mond"
L["NEWVERSION"] = "Eine neue Version von TellMeWhen ist verfügbar: %s"
L["NONE"] = "Keine der Folgenden" -- Needs review
L["normal"] = "normal"
L["OUTLINE_NO"] = "Keine Umrandung"
L["OUTLINE_THICK"] = "Dicke Umrandung"
L["OUTLINE_THIN"] = "Dünne Umrandung"
L["PhysicalDmgTaken"] = "Erhaltener physischer Schaden" -- Needs review
L["Poison"] = "Gift"
L["PushbackResistance"] = "Erhöhter Rückstoßwiderstand "
L["PvPSpells"] = "PVP Gruppenkontrolle, usw."
L["rare"] = "Rar" -- Needs review
L["rareelite"] = "Rar Elite" -- Needs review
L["ReducedArmor"] = "Verringerte Rüstungswertung"
L["ReducedAttackSpeed"] = "Verringerte Angriffsgeschwindigkeit"
L["ReducedCastingSpeed"] = "Verringertes Zaubertempo"
L["ReducedHealing"] = "Verringerte Heilung"
L["ReducedPhysicalDone"] = "Verringerter verursachter physischer Schaden" -- Needs review
L["Resistances"] = "Erhöhter Zauberwiderstand"
L["RESIZE"] = "Größe ändern"
L["RESIZE_TOOLTIP"] = "Klicken und ziehen um die größe zu ändern"
L["RIGHT"] = "rechts" -- Needs review
L["Rooted"] = "Gewurzelt"
L["Shatterable"] = "Zerschlagbar" -- Needs review
L["Silenced"] = "Zum Schweigen gebracht"
L["SORTBY"] = "sortieren nach" -- Needs review
L["SOUND_EVENT_ONSPELL"] = "Wenn Zauberspruch verändert" -- Needs review
L["SOUND_EVENT_ONSPELL_DESC"] = "Dieses Ereignis wird ausgelöst, wenn der Zauberspruch/das Item/etc, für die den/das das Symbol Information darstellt, sich ändert." -- Needs review
L["SOUND_EVENT_ONUNIT"] = "Wenn Einheit verändert" -- Needs review
L["SOUND_EVENT_ONUNIT_DESC"] = "Dieses Ereignis wird ausgelöst, wenn die Einheit, für die das Symbol Information darstellt, sich ändert." -- Needs review
L["SpellCritTaken"] = "Erhöhte, erhaltene kritische Zaubersprüche" -- Needs review
L["SpellDamageTaken"] = "Erhöhter Zauberschaden erhalten"
L["STACKSPANEL_TITLE"] = "Stapel"
L["STRATA_BACKGROUND"] = "Hintergrund" -- Needs review
L["Stunned"] = "Betäubt"
L["SUG_FINISHHIM_DESC"] = "Dies beendet den Caching/Filtering Prozess sofort. Dies könnte den Rechner einige Sekunden einfrieren." -- Needs review
L["SUG_MATCH_WPNENCH_ENCH"] = "Waffe de[sr] (.-)s?$" -- Needs review
L["SUG_PATTERNMATCH_FISHINGLURE"] = "Angelköder %(%+%d+ Angelfertigkeit%)"
L["SUG_PATTERNMATCH_SHARPENINGSTONE"] = "Geschärft %(%+%d+ Schaden%)"
L["SUG_PATTERNMATCH_WEIGHTSTONE"] = "Beschwert %(%+%d+ Schaden%)"
L["SUN"] = "Sonne"
L["TOP"] = "oben" -- Needs review
L["TOPLEFT"] = "oben links" -- Needs review
L["TRUE"] = "Wahr"
L["UIPANEL_ADDGROUP"] = "eine andere Gruppe hinzufügen"
L["UIPANEL_ALLRESET"] = "Alles zurücksetzen"
L["UIPANEL_BARIGNOREGCD"] = "Leisten ignorieren GCD" -- Needs review
L["UIPANEL_BARIGNOREGCD_DESC"] = "Wenn ausgewählt, werden die Abklingzeiten Leisten die Werte nicht ändern wenn die Abklingzeit eine Globale Abklingzeit ist."
L["UIPANEL_BARTEXTURE"] = "Leistentextur"
L["UIPANEL_CLOCKIGNOREGCD"] = "Timer ignoriert Globale Abklingzeiten."
L["UIPANEL_CLOCKIGNOREGCD_DESC"] = "Wenn ausgewählt, werden Timer und Aklingzeiten nicht von der Globalen Abklingzeit ausgelöst."
L["UIPANEL_COLOR_ABSENT"] = "Farbe für Abwesenheit"
L["UIPANEL_COLOR_ABSENT_DESC"] = "Färbung des Symbols wenn Buff / Debuff / Verzauberung / Totem fehlt und \"immer zeigen\" aktiviert ist."
L["UIPANEL_COLOR_COMPLETE"] = "Abklingzeit/Wirkungsdauer abgeschlossen"
L["UIPANEL_COLOR_COMPLETE_DESC"] = "Farbüberlagerung der Leiste, wenn die Abklingzeit / Wirkungsdauer abgeschlossen ist"
L["UIPANEL_COLOR_DESC"] = "Nachfolgende Optionen beeinflussen nur die Farben der Symbole die auf \"immer zeigen\" stehen."
L["UIPANEL_COLOR_OOM"] = "Ende der Ressourcen-Farbe"
L["UIPANEL_COLOR_OOM_DESC"] = "Färbung und Transparenz des Symbols, bei zu wenig Mana / Wut / Energie / Fokus / Runenmacht für den Zauberspruch"
L["UIPANEL_COLOR_OOR"] = "Außer Reichweite-Farbe"
L["UIPANEL_COLOR_OOR_DESC"] = "Färbung und Transparenz des Symbols, wenn nicht in Reichweite zum Ziels um den Zauberspruch zu wirken."
L["UIPANEL_COLOR_PRESENT"] = "Derzeitige Farbe"
L["UIPANEL_COLOR_PRESENT_DESC"] = "Färbung des Symbols wenn Buff / Debuff / Verzauberung / Totem vorhanden und \"immer zeigen\" aktiviert ist."
L["UIPANEL_COLORS"] = "Farben"
L["UIPANEL_COLOR_STARTED"] = "Abklingkeit/Wirkungsdauer-Beginn"
L["UIPANEL_COLOR_STARTED_DESC"] = "Färbung der Leiste, wenn die Abklingzeit /Wirkungsdauer gerade erst begonnen hat"
L["UIPANEL_COLUMNS"] = "Spalten"
L["UIPANEL_DELGROUP"] = "lösche diese Gruppe"
L["UIPANEL_DRAWEDGE"] = "Blinkender Rand-Zeit"
L["UIPANEL_DRAWEDGE_DESC"] = "Blinkender Rand um die Abklingzeit (Uhr-Animation), um die Sichtbarkeit zu erhöhen"
L["UIPANEL_ENABLEGROUP"] = "Gruppe freigeben"
L["UIPANEL_FONT_CONSTRAINWIDTH"] = "Breite beschränken" -- Needs review
L["UIPANEL_FONT_CONSTRAINWIDTH_DESC"] = "Bestätigen Sie dies um den Text zu zwingen innerhalb der Breite des Symbols, sollte dieses korrekt platziert sein, zu passen. Entfernen Sie die Bestätigung um den Text breiter als das Symbol reichen zu lassen." -- Needs review
L["UIPANEL_FONT_DESC"] = "Wähle die Schriftart für den Text von gestapelten Symbolen."
L["UIPANEL_FONT_OUTLINE"] = "Schriftart-Kontur"
L["UIPANEL_FONT_OUTLINE_DESC"] = "Bestimmt den Konturenstil des Stapeltextes, auf Symbolen."
L["UIPANEL_FONT_OVERRIDELBF"] = "ButtonFacade überschreiben" -- Needs review
L["UIPANEL_FONT_SIZE"] = "Zeichengröße"
L["UIPANEL_FONT_SIZE_DESC"] = "Ändert die Größe für die benutzt Schriftart bei gestapelten Symbolen. Wenn ButtonFacade benuzt wird und der ButtonFacade Skin eine vordefinierte Schriftgröße hat, wird diese Einstellung ignoriert." -- Needs review
L["UIPANEL_FONT_XOFFS"] = "X Versatz"
L["UIPANEL_FONT_YOFFS"] = "Y Versatz"
L["UIPANEL_GROUPRESET"] = "Position zurücksetzen"
L["UIPANEL_GROUPS"] = "Gruppen"
L["UIPANEL_ICONSPACING"] = "Abstand der Icon's."
L["UIPANEL_ICONSPACING_DESC"] = "Abstand der Icons' in einer Gruppe."
L["UIPANEL_LOCK"] = "sperre Position" -- Needs review
L["UIPANEL_LOCKUNLOCK"] = "Sperren / Entsperren AddOn"
L["UIPANEL_MAINOPT"] = "Grundeinstellungen"
L["UIPANEL_ONLYINCOMBAT"] = "Nur im Kampf zeigen"
L["UIPANEL_PRIMARYSPEC"] = "Erste Talentspezialisierung"
L["UIPANEL_ROWS"] = "Zeilen"
L["UIPANEL_SECONDARYSPEC"] = "Zweite Talentspezialisierung"
L["UIPANEL_SPEC"] = "Talent Spezialisierung"
L["UIPANEL_SUBTEXT2"] = "Symbole funktionieren im gesperrten Zustand, im entsperrten Zustand kannst du die Symbolgruppen bewegen, die größe ändern und mit einem rechtsklick einzelne Symbole anklicken, für weitere Optionen. Du kannst auch '/tellmewhen' oder /tmw zum sperren / entsperren tippen."
L["UIPANEL_TOOLTIP_ALLRESET"] = "DATEN und POSITIONEN aller Symbole und Gruppen zurücksetzen"
L["UIPANEL_TOOLTIP_COLUMNS"] = "Setzt die Anzahl der Symbolspalten in dieser Gruppe"
L["UIPANEL_TOOLTIP_ENABLEGROUP"] = "Zeige und aktivieren diese Gruppe von Symbolen"
L["UIPANEL_TOOLTIP_GROUPRESET"] = "Position dieser Gruppe zurücksetzen"
L["UIPANEL_TOOLTIP_ONLYINCOMBAT"] = "Aktivieren um nur diese Gruppe von Symbolen im Kampf zu zeigen"
L["UIPANEL_TOOLTIP_PRIMARYSPEC"] = "Aktivieren damit diese Gruppe von Symbolen angezeigt wird, während deine erste Talentspezialisierung aktiv ist"
L["UIPANEL_TOOLTIP_ROWS"] = "Setzt die Anzahl der Symbolreihen in dieser Gruppe"
L["UIPANEL_TOOLTIP_SECONDARYSPEC"] = "Aktivieren damit diese Gruppe von Symbolen angezeigt wird, während deine zweite Talentspezialisierung aktiv ist"
L["UIPANEL_TOOLTIP_UPDATEINTERVAL"] = "Legt fest wie oft (in Sekunden) Symbole auf zeigen/verstecken, alpha, Bedingungen usw. überprüft werden. Beeinträchtigt keine Leisten. Null ist so schnell wie möglich. Niedrigere Werte können erheblichen Einfluss auf die Framerate für Low-End-Rechner haben"
L["UIPANEL_UPDATEINTERVAL"] = "Aktualisierungs-Interval"
L["worldboss"] = "Weltboss"
