--[[
************************************************************************
ptBR.lua
ptBR localization strings for Ackis Recipe List
************************************************************************
File date: 2011-09-04T15:07:34Z 
File revision: @file-revision@ 
Project revision: @project-revision@
Project version: 2.2.10
************************************************************************
Currently maintained by:
http://www.wowace.com/addons/arl/localization/translators/

Please update http://www.wowace.com/addons/arl/localization/ptBR/ for any translation
additions or changes.

The translations will be auto-generated by the localization application.

Please make sure you update the ToC file with any translations.
************************************************************************
Please see http://www.wowace.com/addons/arl/ for more information.
************************************************************************
These translations are released under the Public Domain.
************************************************************************
]]--

local L = LibStub("AceLocale-3.0"):NewLocale("Ackis Recipe List", "ptBR", false)

if not L then return end

L["\"Cookie\" McWeaksauce"] = "\"Biscoito\" McMolhofraco" -- Needs review
L["ALL_FILTERED"] = "Apesar de você já ter escaneado esta profissão, seus filtros impedem a exibição de qualquer receita. Por favor, altere seus filtros e tente novamente." -- Needs review
L["ALT_CLICK"] = "Alt-Clique para adicionar/remover esta receita de sua lista de ignoradas." -- Needs review
L["ARL_ALLEXCLUDED"] = "Apesar de você já ter escaneado esta profissão, suas exceções impedem a exibição de qualquer receita. Por favor, altere suas exceções e tente novamente." -- Needs review
L["ARL_ALLKNOWN"] = "Você sabe todas as receitas desta profissão." -- Needs review
L["AXE_DESC"] = "Receitas que produzem machados devem ser incluídos no escaneamento."
L["About"] = "Sobre" -- Needs review
L["Acquisition"] = "Aquisição" -- Needs review
L["Aged Dalaran Wizard"] = "Mago Idoso de Dalaran" -- Needs review
L["Are We There, Yeti?"] = "Já Chegamos, Yeti?" -- Needs review
L["Axe"] = "Machado"
L["BOAFilter"] = "Item Ligado à Conta" -- Needs review
L["BOA_DESC"] = "Receitas que criem itens que Ligam à Conta serão incluídas no escaneamento." -- Needs review
L["BOEFilter"] = "Item Ligado ao Equipar" -- Needs review
L["BOE_DESC"] = "Receitas que criem itens que Ligam ao Equipar serão incluídas no escaneamento." -- Needs review
L["BOPFilter"] = "Item Liga ao Pegar" -- Needs review
L["BOP_DESC"] = "Receitas que criem itens que Ligam ao Pegar serão incluídas no escaneamento." -- Needs review
L["BOW_DESC"] = "Receitas que criem arcos serão incluídas no escaneamento." -- Needs review
L["Bow"] = "Arco" -- Needs review
L["CLASS_DESC"] = "Inclui esta classe no escaneamento. Isto filtrará em dois fatores: 1) Se a classe pode usar esta receita e 2) Se a classe pode aprender esta receita" -- Needs review
L["CLOAK_DESC"] = "Receitas que criem capas serão incluídas no escaneamento." -- Needs review
L["CLOSEGUI_DESC"] = "Fechar a janela ARL quando a janela da profissão for fechada." -- Needs review
L["CLOSE_DESC"] = "Fechar a janela da Lista de Receitas." -- Needs review
L["CLOTH_DESC"] = "Receitas que criem pano serão incluídas no escaneamento." -- Needs review
L["COMMON_ISSUES_DESC"] = [=[Por favor, verifique estes problemas comuns antes de submeter um relatório de erro
1) Receita X não aparece! - Verifique suas configurações de filtro para certificar-se de que a receita não foi filtrada.
2) Faltam vários glifos para Escrivão! Por quê não estão na lista?  Desabilite seu filtro de "classes". Por padrão (e devido a pedidos populares) ARL somente mostrará receitas que a sua classe pode usar e a maioria dos glifos não são utilizáveis pela sua classe.
3) Eu não quero ver as receitas da facção oposta! Ligue o filtro de facção. Isto fará com que a lista tenha somente receitas adquiríveis pela sua facção. Se ainda aparecer algo que não deveria, por favor encaminhe um relatório de erros.]=] -- Needs review
L["CONTRACTALL_DESC"] = "Minimizar todas as receitas listadas abaixo" -- Needs review
L["CTRL_CLICK"] = "Ctrl-Clique para adicionar o link desta receita ao bate-papo." -- Needs review
L["Classes"] = true -- Needs review
L["Cloak"] = "Capa" -- Needs review
L["Close GUI"] = "Fechar com Tradeskill UI" -- Needs review
L["Cloth"] = "Pano" -- Needs review
L["Common Issues"] = "Problemas comuns" -- Needs review
L["DAGGER_DESC"] = "Receitas que criem adaga serão incluídas no escaneamento." -- Needs review
L["Dagger"] = "Adaga" -- Needs review
L["Mace"] = "Bastão" -- Needs review
L["Obtain"] = "Obter"
L["Obtained From"] = "Obtido de"
L["One Hand"] = "Uma Mão" -- Needs review
L["Profile Options"] = "Opções do perfil"
L["UNKNOWN_DESC"] = "Incluir todas as receitas desconhecidas no escaneamento."
